// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: live_revenue.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createWalletAccount = `-- name: CreateWalletAccount :exec
INSERT INTO wallet_accounts (user_id, currency, available_balance)
VALUES (?, 'COIN', 0)
`

func (q *Queries) CreateWalletAccount(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, createWalletAccount, userID)
	return err
}

const getGiftCatalogItem = `-- name: GetGiftCatalogItem :one
SELECT gift_id, display_name, coin_price, match_points, diamond_reward, enabled
FROM gift_catalog
WHERE gift_id = ?
`

type GetGiftCatalogItemRow struct {
	GiftID        string
	DisplayName   string
	CoinPrice     uint32
	MatchPoints   uint32
	DiamondReward uint32
	Enabled       bool
}

func (q *Queries) GetGiftCatalogItem(ctx context.Context, giftID string) (GetGiftCatalogItemRow, error) {
	row := q.db.QueryRowContext(ctx, getGiftCatalogItem, giftID)
	var i GetGiftCatalogItemRow
	err := row.Scan(
		&i.GiftID,
		&i.DisplayName,
		&i.CoinPrice,
		&i.MatchPoints,
		&i.DiamondReward,
		&i.Enabled,
	)
	return i, err
}

const getGiftOrderByRequest = `-- name: GetGiftOrderByRequest :one
SELECT gift_order_id, viewer_id, creator_id, live_session_id, match_id, gift_id, quantity,
       charged_coins, match_points_added, diamond_reward, post_balance, status, reject_code, request_id,
       body_hash, created_at
FROM gift_orders
WHERE viewer_id = ? AND request_id = ?
`

type GetGiftOrderByRequestParams struct {
	ViewerID  uint64
	RequestID string
}

func (q *Queries) GetGiftOrderByRequest(ctx context.Context, arg GetGiftOrderByRequestParams) (GiftOrder, error) {
	row := q.db.QueryRowContext(ctx, getGiftOrderByRequest, arg.ViewerID, arg.RequestID)
	var i GiftOrder
	err := row.Scan(
		&i.GiftOrderID,
		&i.ViewerID,
		&i.CreatorID,
		&i.LiveSessionID,
		&i.MatchID,
		&i.GiftID,
		&i.Quantity,
		&i.ChargedCoins,
		&i.MatchPointsAdded,
		&i.DiamondReward,
		&i.PostBalance,
		&i.Status,
		&i.RejectCode,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getLiveMatch = `-- name: GetLiveMatch :one
SELECT match_id, live_session_id, mode, specific_gift_id, status
FROM live_matches
WHERE match_id = ?
`

func (q *Queries) GetLiveMatch(ctx context.Context, matchID uint64) (LiveMatch, error) {
	row := q.db.QueryRowContext(ctx, getLiveMatch, matchID)
	var i LiveMatch
	err := row.Scan(
		&i.MatchID,
		&i.LiveSessionID,
		&i.Mode,
		&i.SpecificGiftID,
		&i.Status,
	)
	return i, err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT live_session_id, creator_id, campaign_id, status, started_at, closed_at
FROM live_sessions
WHERE live_session_id = ?
`

func (q *Queries) GetLiveSession(ctx context.Context, liveSessionID uint64) (LiveSession, error) {
	row := q.db.QueryRowContext(ctx, getLiveSession, liveSessionID)
	var i LiveSession
	err := row.Scan(
		&i.LiveSessionID,
		&i.CreatorID,
		&i.CampaignID,
		&i.Status,
		&i.StartedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getRechargeRequest = `-- name: GetRechargeRequest :one
SELECT viewer_id, request_id, body_hash, coins, payment_ref, resulting_balance, tx_id, created_at
FROM recharge_requests
WHERE viewer_id = ? AND request_id = ?
`

type GetRechargeRequestParams struct {
	ViewerID  uint64
	RequestID string
}

func (q *Queries) GetRechargeRequest(ctx context.Context, arg GetRechargeRequestParams) (RechargeRequest, error) {
	row := q.db.QueryRowContext(ctx, getRechargeRequest, arg.ViewerID, arg.RequestID)
	var i RechargeRequest
	err := row.Scan(
		&i.ViewerID,
		&i.RequestID,
		&i.BodyHash,
		&i.Coins,
		&i.PaymentRef,
		&i.ResultingBalance,
		&i.TxID,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, age_years, region_code, account_standing, can_go_live, live_gifts_enabled, account_type
FROM users
WHERE user_id = ?
`

type GetUserRow struct {
	UserID           uint64
	AgeYears         uint8
	RegionCode       string
	AccountStanding  UsersAccountStanding
	CanGoLive        bool
	LiveGiftsEnabled bool
	AccountType      UsersAccountType
}

func (q *Queries) GetUser(ctx context.Context, userID uint64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i GetUserRow
	err := row.Scan(
		&i.UserID,
		&i.AgeYears,
		&i.RegionCode,
		&i.AccountStanding,
		&i.CanGoLive,
		&i.LiveGiftsEnabled,
		&i.AccountType,
	)
	return i, err
}

const getWalletAccountForUpdate = `-- name: GetWalletAccountForUpdate :one
SELECT user_id, currency, available_balance
FROM wallet_accounts
WHERE user_id = ? AND currency = 'COIN'
FOR UPDATE
`

type GetWalletAccountForUpdateRow struct {
	UserID           uint64
	Currency         WalletAccountsCurrency
	AvailableBalance int64
}

func (q *Queries) GetWalletAccountForUpdate(ctx context.Context, userID uint64) (GetWalletAccountForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getWalletAccountForUpdate, userID)
	var i GetWalletAccountForUpdateRow
	err := row.Scan(&i.UserID, &i.Currency, &i.AvailableBalance)
	return i, err
}

const insertGiftOrder = `-- name: InsertGiftOrder :execresult
INSERT INTO gift_orders (
    viewer_id, creator_id, live_session_id, match_id, gift_id, quantity,
    charged_coins, match_points_added, diamond_reward, post_balance, status, reject_code,
    request_id, body_hash, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertGiftOrderParams struct {
	ViewerID         uint64
	CreatorID        uint64
	LiveSessionID    uint64
	MatchID          sql.NullInt64
	GiftID           string
	Quantity         uint16
	ChargedCoins     uint32
	MatchPointsAdded uint32
	DiamondReward    uint32
	PostBalance      sql.NullInt64
	Status           GiftOrdersStatus
	RejectCode       sql.NullString
	RequestID        string
	BodyHash         []byte
	CreatedAt        time.Time
}

func (q *Queries) InsertGiftOrder(ctx context.Context, arg InsertGiftOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertGiftOrder,
		arg.ViewerID,
		arg.CreatorID,
		arg.LiveSessionID,
		arg.MatchID,
		arg.GiftID,
		arg.Quantity,
		arg.ChargedCoins,
		arg.MatchPointsAdded,
		arg.DiamondReward,
		arg.PostBalance,
		arg.Status,
		arg.RejectCode,
		arg.RequestID,
		arg.BodyHash,
		arg.CreatedAt,
	)
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :execresult
INSERT INTO outbox_events (topic, event_key, payload_json, created_at)
VALUES (?, ?, ?, ?)
`

type InsertOutboxEventParams struct {
	Topic       string
	EventKey    string
	PayloadJson json.RawMessage
	CreatedAt   time.Time
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertOutboxEvent,
		arg.Topic,
		arg.EventKey,
		arg.PayloadJson,
		arg.CreatedAt,
	)
}

const insertRechargeRequest = `-- name: InsertRechargeRequest :exec
INSERT INTO recharge_requests (viewer_id, request_id, body_hash, coins, payment_ref, resulting_balance, tx_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRechargeRequestParams struct {
	ViewerID         uint64
	RequestID        string
	BodyHash         []byte
	Coins            uint32
	PaymentRef       string
	ResultingBalance int64
	TxID             uint64
	CreatedAt        time.Time
}

func (q *Queries) InsertRechargeRequest(ctx context.Context, arg InsertRechargeRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertRechargeRequest,
		arg.ViewerID,
		arg.RequestID,
		arg.BodyHash,
		arg.Coins,
		arg.PaymentRef,
		arg.ResultingBalance,
		arg.TxID,
		arg.CreatedAt,
	)
	return err
}

const insertWalletEntry = `-- name: InsertWalletEntry :exec
INSERT INTO wallet_entries (tx_id, account_code, amount)
VALUES (?, ?, ?)
`

type InsertWalletEntryParams struct {
	TxID        uint64
	AccountCode string
	Amount      int64
}

func (q *Queries) InsertWalletEntry(ctx context.Context, arg InsertWalletEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertWalletEntry, arg.TxID, arg.AccountCode, arg.Amount)
	return err
}

const insertWalletTransaction = `-- name: InsertWalletTransaction :execresult
INSERT INTO wallet_transactions (tx_type, actor_user_id, request_id, body_hash, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertWalletTransactionParams struct {
	TxType      WalletTransactionsTxType
	ActorUserID uint64
	RequestID   string
	BodyHash    sql.NullString
	CreatedAt   time.Time
}

func (q *Queries) InsertWalletTransaction(ctx context.Context, arg InsertWalletTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertWalletTransaction,
		arg.TxType,
		arg.ActorUserID,
		arg.RequestID,
		arg.BodyHash,
		arg.CreatedAt,
	)
}

const markLiveSessionClosed = `-- name: MarkLiveSessionClosed :exec
UPDATE live_sessions
SET status = 'CLOSED', closed_at = ?
WHERE live_session_id = ? AND status = 'OPEN'
`

type MarkLiveSessionClosedParams struct {
	ClosedAt      sql.NullTime
	LiveSessionID uint64
}

func (q *Queries) MarkLiveSessionClosed(ctx context.Context, arg MarkLiveSessionClosedParams) error {
	_, err := q.db.ExecContext(ctx, markLiveSessionClosed, arg.ClosedAt, arg.LiveSessionID)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox_events
SET published_at = ?
WHERE event_id = ?
`

type MarkOutboxPublishedParams struct {
	PublishedAt sql.NullTime
	EventID     uint64
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxPublished, arg.PublishedAt, arg.EventID)
	return err
}

const selectOutboxBatchForPublish = `-- name: SelectOutboxBatchForPublish :many
SELECT event_id, topic, event_key, payload_json, created_at
FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at ASC
LIMIT ?
FOR UPDATE SKIP LOCKED
`

type SelectOutboxBatchForPublishRow struct {
	EventID     uint64
	Topic       string
	EventKey    string
	PayloadJson json.RawMessage
	CreatedAt   time.Time
}

func (q *Queries) SelectOutboxBatchForPublish(ctx context.Context, limit int32) ([]SelectOutboxBatchForPublishRow, error) {
	rows, err := q.db.QueryContext(ctx, selectOutboxBatchForPublish, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectOutboxBatchForPublishRow
	for rows.Next() {
		var i SelectOutboxBatchForPublishRow
		if err := rows.Scan(
			&i.EventID,
			&i.Topic,
			&i.EventKey,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallet_accounts
SET available_balance = ?
WHERE user_id = ? AND currency = 'COIN'
`

type UpdateWalletBalanceParams struct {
	AvailableBalance int64
	UserID           uint64
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateWalletBalance, arg.AvailableBalance, arg.UserID)
	return err
}

const upsertReconciliation = `-- name: UpsertReconciliation :exec
INSERT INTO reconciliation_results (
    live_session_id, status, wallet_gift_debit_total, gift_order_coin_total, mismatch_count, details_json, generated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    status = VALUES(status),
    wallet_gift_debit_total = VALUES(wallet_gift_debit_total),
    gift_order_coin_total = VALUES(gift_order_coin_total),
    mismatch_count = VALUES(mismatch_count),
    details_json = VALUES(details_json),
    generated_at = VALUES(generated_at)
`

type UpsertReconciliationParams struct {
	LiveSessionID        uint64
	Status               ReconciliationResultsStatus
	WalletGiftDebitTotal int64
	GiftOrderCoinTotal   int64
	MismatchCount        int32
	DetailsJson          json.RawMessage
	GeneratedAt          time.Time
}

func (q *Queries) UpsertReconciliation(ctx context.Context, arg UpsertReconciliationParams) error {
	_, err := q.db.ExecContext(ctx, upsertReconciliation,
		arg.LiveSessionID,
		arg.Status,
		arg.WalletGiftDebitTotal,
		arg.GiftOrderCoinTotal,
		arg.MismatchCount,
		arg.DetailsJson,
		arg.GeneratedAt,
	)
	return err
}

const upsertSettlement = `-- name: UpsertSettlement :exec
INSERT INTO stream_settlements (live_session_id, gross_coin_spend, accepted_gift_count, diamond_reward_total, generated_at)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    gross_coin_spend = VALUES(gross_coin_spend),
    accepted_gift_count = VALUES(accepted_gift_count),
    diamond_reward_total = VALUES(diamond_reward_total),
    generated_at = VALUES(generated_at)
`

type UpsertSettlementParams struct {
	LiveSessionID      uint64
	GrossCoinSpend     int64
	AcceptedGiftCount  int64
	DiamondRewardTotal int64
	GeneratedAt        time.Time
}

func (q *Queries) UpsertSettlement(ctx context.Context, arg UpsertSettlementParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettlement,
		arg.LiveSessionID,
		arg.GrossCoinSpend,
		arg.AcceptedGiftCount,
		arg.DiamondRewardTotal,
		arg.GeneratedAt,
	)
	return err
}
