// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type CampaignPointLedgerReason string

const (
	CampaignPointLedgerReasonGIFT CampaignPointLedgerReason = "GIFT"
)

func (e *CampaignPointLedgerReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignPointLedgerReason(s)
	case string:
		*e = CampaignPointLedgerReason(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignPointLedgerReason: %T", src)
	}
	return nil
}

type NullCampaignPointLedgerReason struct {
	CampaignPointLedgerReason CampaignPointLedgerReason
	Valid                     bool // Valid is true if CampaignPointLedgerReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignPointLedgerReason) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignPointLedgerReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignPointLedgerReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignPointLedgerReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignPointLedgerReason), nil
}

type FanPointLedgerReason string

const (
	FanPointLedgerReasonGIFT        FanPointLedgerReason = "GIFT"
	FanPointLedgerReasonCOMMENT     FanPointLedgerReason = "COMMENT"
	FanPointLedgerReasonWATCHMINUTE FanPointLedgerReason = "WATCH_MINUTE"
)

func (e *FanPointLedgerReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FanPointLedgerReason(s)
	case string:
		*e = FanPointLedgerReason(s)
	default:
		return fmt.Errorf("unsupported scan type for FanPointLedgerReason: %T", src)
	}
	return nil
}

type NullFanPointLedgerReason struct {
	FanPointLedgerReason FanPointLedgerReason
	Valid                bool // Valid is true if FanPointLedgerReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFanPointLedgerReason) Scan(value interface{}) error {
	if value == nil {
		ns.FanPointLedgerReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FanPointLedgerReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFanPointLedgerReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FanPointLedgerReason), nil
}

type GiftOrdersStatus string

const (
	GiftOrdersStatusACCEPTED GiftOrdersStatus = "ACCEPTED"
	GiftOrdersStatusREJECTED GiftOrdersStatus = "REJECTED"
)

func (e *GiftOrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GiftOrdersStatus(s)
	case string:
		*e = GiftOrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GiftOrdersStatus: %T", src)
	}
	return nil
}

type NullGiftOrdersStatus struct {
	GiftOrdersStatus GiftOrdersStatus
	Valid            bool // Valid is true if GiftOrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGiftOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GiftOrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GiftOrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGiftOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GiftOrdersStatus), nil
}

type LiveMatchesMode string

const (
	LiveMatchesModeALLGIFTS     LiveMatchesMode = "ALL_GIFTS"
	LiveMatchesModeSPECIFICGIFT LiveMatchesMode = "SPECIFIC_GIFT"
)

func (e *LiveMatchesMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LiveMatchesMode(s)
	case string:
		*e = LiveMatchesMode(s)
	default:
		return fmt.Errorf("unsupported scan type for LiveMatchesMode: %T", src)
	}
	return nil
}

type NullLiveMatchesMode struct {
	LiveMatchesMode LiveMatchesMode
	Valid           bool // Valid is true if LiveMatchesMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLiveMatchesMode) Scan(value interface{}) error {
	if value == nil {
		ns.LiveMatchesMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LiveMatchesMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLiveMatchesMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LiveMatchesMode), nil
}

type LiveMatchesStatus string

const (
	LiveMatchesStatusOPEN   LiveMatchesStatus = "OPEN"
	LiveMatchesStatusCLOSED LiveMatchesStatus = "CLOSED"
)

func (e *LiveMatchesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LiveMatchesStatus(s)
	case string:
		*e = LiveMatchesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LiveMatchesStatus: %T", src)
	}
	return nil
}

type NullLiveMatchesStatus struct {
	LiveMatchesStatus LiveMatchesStatus
	Valid             bool // Valid is true if LiveMatchesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLiveMatchesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LiveMatchesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LiveMatchesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLiveMatchesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LiveMatchesStatus), nil
}

type LiveSessionsStatus string

const (
	LiveSessionsStatusOPEN   LiveSessionsStatus = "OPEN"
	LiveSessionsStatusCLOSED LiveSessionsStatus = "CLOSED"
)

func (e *LiveSessionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LiveSessionsStatus(s)
	case string:
		*e = LiveSessionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LiveSessionsStatus: %T", src)
	}
	return nil
}

type NullLiveSessionsStatus struct {
	LiveSessionsStatus LiveSessionsStatus
	Valid              bool // Valid is true if LiveSessionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLiveSessionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LiveSessionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LiveSessionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLiveSessionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LiveSessionsStatus), nil
}

type ReconciliationResultsStatus string

const (
	ReconciliationResultsStatusPASS ReconciliationResultsStatus = "PASS"
	ReconciliationResultsStatusFAIL ReconciliationResultsStatus = "FAIL"
)

func (e *ReconciliationResultsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReconciliationResultsStatus(s)
	case string:
		*e = ReconciliationResultsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReconciliationResultsStatus: %T", src)
	}
	return nil
}

type NullReconciliationResultsStatus struct {
	ReconciliationResultsStatus ReconciliationResultsStatus
	Valid                       bool // Valid is true if ReconciliationResultsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReconciliationResultsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReconciliationResultsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReconciliationResultsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReconciliationResultsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReconciliationResultsStatus), nil
}

type UsersAccountStanding string

const (
	UsersAccountStandingGOOD       UsersAccountStanding = "GOOD"
	UsersAccountStandingRESTRICTED UsersAccountStanding = "RESTRICTED"
	UsersAccountStandingBANNED     UsersAccountStanding = "BANNED"
)

func (e *UsersAccountStanding) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersAccountStanding(s)
	case string:
		*e = UsersAccountStanding(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersAccountStanding: %T", src)
	}
	return nil
}

type NullUsersAccountStanding struct {
	UsersAccountStanding UsersAccountStanding
	Valid                bool // Valid is true if UsersAccountStanding is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersAccountStanding) Scan(value interface{}) error {
	if value == nil {
		ns.UsersAccountStanding, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersAccountStanding.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersAccountStanding) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersAccountStanding), nil
}

type UsersAccountType string

const (
	UsersAccountTypeNORMAL         UsersAccountType = "NORMAL"
	UsersAccountTypeGOVERNMENT     UsersAccountType = "GOVERNMENT"
	UsersAccountTypePOLITICIAN     UsersAccountType = "POLITICIAN"
	UsersAccountTypePOLITICALPARTY UsersAccountType = "POLITICAL_PARTY"
	UsersAccountTypePUBLICINTEREST UsersAccountType = "PUBLIC_INTEREST"
)

func (e *UsersAccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersAccountType(s)
	case string:
		*e = UsersAccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersAccountType: %T", src)
	}
	return nil
}

type NullUsersAccountType struct {
	UsersAccountType UsersAccountType
	Valid            bool // Valid is true if UsersAccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.UsersAccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersAccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersAccountType), nil
}

type WalletAccountsCurrency string

const (
	WalletAccountsCurrencyCOIN WalletAccountsCurrency = "COIN"
)

func (e *WalletAccountsCurrency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletAccountsCurrency(s)
	case string:
		*e = WalletAccountsCurrency(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletAccountsCurrency: %T", src)
	}
	return nil
}

type NullWalletAccountsCurrency struct {
	WalletAccountsCurrency WalletAccountsCurrency
	Valid                  bool // Valid is true if WalletAccountsCurrency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletAccountsCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.WalletAccountsCurrency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletAccountsCurrency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletAccountsCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletAccountsCurrency), nil
}

type WalletTransactionsTxType string

const (
	WalletTransactionsTxTypeRECHARGE  WalletTransactionsTxType = "RECHARGE"
	WalletTransactionsTxTypeGIFTDEBIT WalletTransactionsTxType = "GIFT_DEBIT"
)

func (e *WalletTransactionsTxType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletTransactionsTxType(s)
	case string:
		*e = WalletTransactionsTxType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletTransactionsTxType: %T", src)
	}
	return nil
}

type NullWalletTransactionsTxType struct {
	WalletTransactionsTxType WalletTransactionsTxType
	Valid                    bool // Valid is true if WalletTransactionsTxType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletTransactionsTxType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletTransactionsTxType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletTransactionsTxType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletTransactionsTxType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletTransactionsTxType), nil
}

type CampaignPointLedger struct {
	EventID    uint64
	CampaignID uint64
	CreatorID  uint64
	Points     int32
	Reason     CampaignPointLedgerReason
	CreatedAt  time.Time
}

type ConsumerDedupe struct {
	ConsumerName string
	EventID      uint64
	AppliedAt    time.Time
}

type FanPointLedger struct {
	EventID       uint64
	ViewerID      uint64
	CreatorID     uint64
	LiveSessionID uint64
	Points        int32
	Reason        FanPointLedgerReason
	CreatedAt     time.Time
}

type GiftCatalog struct {
	GiftID        string
	DisplayName   string
	CoinPrice     uint32
	MatchPoints   uint32
	DiamondReward uint32
	Enabled       bool
	CreatedAt     time.Time
}

type GiftOrder struct {
	GiftOrderID      uint64
	ViewerID         uint64
	CreatorID        uint64
	LiveSessionID    uint64
	MatchID          sql.NullInt64
	GiftID           string
	Quantity         uint16
	ChargedCoins     uint32
	MatchPointsAdded uint32
	DiamondReward    uint32
	PostBalance      sql.NullInt64
	Status           GiftOrdersStatus
	RejectCode       sql.NullString
	RequestID        string
	BodyHash         []byte
	CreatedAt        time.Time
}

type LiveMatch struct {
	MatchID        uint64
	LiveSessionID  uint64
	Mode           LiveMatchesMode
	SpecificGiftID sql.NullString
	Status         LiveMatchesStatus
}

type LiveSession struct {
	LiveSessionID uint64
	CreatorID     uint64
	CampaignID    sql.NullInt64
	Status        LiveSessionsStatus
	StartedAt     time.Time
	ClosedAt      sql.NullTime
}

type OutboxEvent struct {
	EventID     uint64
	Topic       string
	EventKey    string
	PayloadJson json.RawMessage
	PublishedAt sql.NullTime
	CreatedAt   time.Time
}

type RechargeRequest struct {
	ViewerID         uint64
	RequestID        string
	BodyHash         []byte
	Coins            uint32
	PaymentRef       string
	ResultingBalance int64
	TxID             uint64
	CreatedAt        time.Time
}

type ReconciliationResult struct {
	LiveSessionID        uint64
	Status               ReconciliationResultsStatus
	WalletGiftDebitTotal int64
	GiftOrderCoinTotal   int64
	MismatchCount        int32
	DetailsJson          json.RawMessage
	GeneratedAt          time.Time
}

type StreamSettlement struct {
	LiveSessionID      uint64
	GrossCoinSpend     int64
	AcceptedGiftCount  int64
	DiamondRewardTotal int64
	GeneratedAt        time.Time
}

type User struct {
	UserID           uint64
	AgeYears         uint8
	RegionCode       string
	AccountStanding  UsersAccountStanding
	CanGoLive        bool
	LiveGiftsEnabled bool
	AccountType      UsersAccountType
	CreatedAt        time.Time
}

type WalletAccount struct {
	UserID           uint64
	Currency         WalletAccountsCurrency
	AvailableBalance int64
	UpdatedAt        time.Time
}

type WalletEntry struct {
	TxID        uint64
	AccountCode string
	Amount      int64
}

type WalletTransaction struct {
	TxID        uint64
	TxType      WalletTransactionsTxType
	ActorUserID uint64
	RequestID   string
	BodyHash    sql.NullString
	CreatedAt   time.Time
}
