global:
  scrape_interval: 5s
scrape_configs:
  - job_name: api
    static_configs:
      - targets: ["api:8080"]
  - job_name: leaderboard_projector
    static_configs:
      - targets: ["leaderboard-projector:9101"]
  - job_name: points_projector
    static_configs:
      - targets: ["points-projector:9102"]
